-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS akkurim.athlete_status
(
    id uuid NOT NULL,
    name text NOT NULL,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.guardian
(
    id uuid NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.item_type
(
    id uuid NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.item
(
    id uuid NOT NULL,
    name text NOT NULL,
    description text,
    image text,
    count smallint NOT NULL,
    item_type_id uuid NOT NULL,
    athlete_id uuid,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.athlete
(
    id uuid NOT NULL,
    birth_number text NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    street text NOT NULL,
    city text NOT NULL,
    zip text NOT NULL,
    email text,
    phone text,
    ean text,
    note text,
    athlete_status_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.athlete_guardian
(
    athlete_id uuid NOT NULL,
    guardian_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS akkurim.trainer_status
(
    id uuid NOT NULL,
    name text NOT NULL,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.trainer
(
    id uuid NOT NULL,
    athlete_id uuid NOT NULL,
    trainer_status_id uuid NOT NULL,
    qualification text NOT NULL,
    salary_per_hour smallint NOT NULL,
    device_token text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (athlete_id)
);

CREATE TABLE IF NOT EXISTS akkurim.athlete_item
(
    athlete_id uuid NOT NULL,
    item_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS akkurim.school_year
(
    id uuid NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.web_post
(
    id uuid NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    trainer_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim."group"
(
    id uuid NOT NULL,
    name text NOT NULL,
    description text,
    training_time_id uuid NOT NULL,
    school_year_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.group_athlete
(
    group_id uuid NOT NULL,
    athlete_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS akkurim.group_trainer
(
    group_id uuid NOT NULL,
    trainer_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS akkurim.training
(
    id uuid NOT NULL,
    datetime_ timestamp with time zone NOT NULL,
    group_id uuid NOT NULL,
    description text,
    duration_minutes smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.training_time
(
    id uuid NOT NULL,
    day text NOT NULL,
    summer_time time with time zone NOT NULL,
    winter_time time with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.training_athlete
(
    training_id uuid NOT NULL,
    athlete_id uuid NOT NULL,
    presence text NOT NULL
);

CREATE TABLE IF NOT EXISTS akkurim.training_trainer
(
    training_id uuid NOT NULL,
    trainer_id uuid NOT NULL,
    presence text
);

CREATE TABLE IF NOT EXISTS akkurim.sign_up_form
(
    id uuid NOT NULL,
    birth_number text NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    street text NOT NULL,
    city text NOT NULL,
    zip text NOT NULL,
    email text,
    phone text,
    guardian_first_name1 text NOT NULL,
    guardian_last_name1 text NOT NULL,
    guardian_first_name2 text,
    guardian_last_name2 text,
    guardian_phone1 text NOT NULL,
    guardian_email1 text NOT NULL,
    guardian_phone2 text,
    guardian_email2 text,
    note text,
    sign_up_form_status_id uuid NOT NULL,
    school_year_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.sign_up_form_status
(
    id uuid NOT NULL,
    name text NOT NULL,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.discipline
(
    id smallint NOT NULL,
    discipline_type_id smallint NOT NULL,
    description text NOT NULL,
    short_description text NOT NULL,
    description_en text NOT NULL,
    short_description_en text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.discipline_type
(
    id smallint NOT NULL,
    name text NOT NULL,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.meet
(
    id text NOT NULL,
    name text NOT NULL,
    start timestamp with time zone NOT NULL,
    "end" timestamp with time zone NOT NULL,
    location text,
    organizer text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.meet_event
(
    id uuid NOT NULL,
    meet_id text NOT NULL,
    meet_type text NOT NULL,
    discipline_id smallint NOT NULL,
    category_id smallint NOT NULL,
    start timestamp with time zone NOT NULL,
    phase text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.category
(
    id smallint NOT NULL,
    sex smallint NOT NULL,
    description text NOT NULL,
    short_description text NOT NULL,
    description_en text NOT NULL,
    short_description_en text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS akkurim.athlete_meet_event
(
    athlete_id uuid NOT NULL,
    meet_event_id uuid NOT NULL,
    result text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS akkurim.athlete_sign_up_form
(
    athlete_id uuid NOT NULL,
    sign_up_form_id uuid NOT NULL
);

ALTER TABLE IF EXISTS akkurim.item
    ADD FOREIGN KEY (item_type_id)
    REFERENCES akkurim.item_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.athlete
    ADD FOREIGN KEY (athlete_status_id)
    REFERENCES akkurim.athlete_status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.athlete_guardian
    ADD FOREIGN KEY (athlete_id)
    REFERENCES akkurim.athlete (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.athlete_guardian
    ADD FOREIGN KEY (guardian_id)
    REFERENCES akkurim.guardian (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.trainer
    ADD FOREIGN KEY (athlete_id)
    REFERENCES akkurim.athlete (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.trainer
    ADD FOREIGN KEY (trainer_status_id)
    REFERENCES akkurim.trainer_status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.athlete_item
    ADD FOREIGN KEY (athlete_id)
    REFERENCES akkurim.athlete (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.athlete_item
    ADD FOREIGN KEY (item_id)
    REFERENCES akkurim.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.web_post
    ADD FOREIGN KEY (trainer_id)
    REFERENCES akkurim.trainer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim."group"
    ADD FOREIGN KEY (school_year_id)
    REFERENCES akkurim.school_year (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim."group"
    ADD FOREIGN KEY (training_time_id)
    REFERENCES akkurim.training_time (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.group_athlete
    ADD FOREIGN KEY (group_id)
    REFERENCES akkurim."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.group_athlete
    ADD FOREIGN KEY (athlete_id)
    REFERENCES akkurim.athlete (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.group_trainer
    ADD FOREIGN KEY (group_id)
    REFERENCES akkurim."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.group_trainer
    ADD FOREIGN KEY (trainer_id)
    REFERENCES akkurim.trainer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.training
    ADD FOREIGN KEY (group_id)
    REFERENCES akkurim."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.training_athlete
    ADD FOREIGN KEY (training_id)
    REFERENCES akkurim.training (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.training_athlete
    ADD FOREIGN KEY (athlete_id)
    REFERENCES akkurim.athlete (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.training_trainer
    ADD FOREIGN KEY (training_id)
    REFERENCES akkurim.training (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.training_trainer
    ADD FOREIGN KEY (trainer_id)
    REFERENCES akkurim.trainer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.sign_up_form
    ADD FOREIGN KEY (sign_up_form_status_id)
    REFERENCES akkurim.sign_up_form_status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.sign_up_form
    ADD FOREIGN KEY (school_year_id)
    REFERENCES akkurim.school_year (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.discipline
    ADD FOREIGN KEY (discipline_type_id)
    REFERENCES akkurim.discipline_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.meet_event
    ADD FOREIGN KEY (category_id)
    REFERENCES akkurim.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.meet_event
    ADD FOREIGN KEY (discipline_id)
    REFERENCES akkurim.discipline (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.meet_event
    ADD FOREIGN KEY (meet_id)
    REFERENCES akkurim.meet (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.meet_event
    ADD FOREIGN KEY (meet_type)
    REFERENCES akkurim.meet (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.athlete_meet_event
    ADD FOREIGN KEY (athlete_id)
    REFERENCES akkurim.athlete (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.athlete_meet_event
    ADD FOREIGN KEY (meet_event_id)
    REFERENCES akkurim.meet_event (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.athlete_sign_up_form
    ADD FOREIGN KEY (athlete_id)
    REFERENCES akkurim.athlete (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS akkurim.athlete_sign_up_form
    ADD FOREIGN KEY (sign_up_form_id)
    REFERENCES akkurim.sign_up_form (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;